//Nombre: Santiago Chaparro Riaño
//Fecha: 15 de abril del 2024
//Trabajo: Contar hazta 5
function contar(pnum){
    let numero = pnum;
    let contador = 0;
    while(numero>contador){
        contador++
        console.log(contador)
    }
    return contador
}

// Como Exp
const contarExp=function(pnum){
    let numero = pnum;
    let contador = 0;
    while(numero>contador){
        contador++
        console.log(contador)
    }
    return contador
}

